# Generated by Django 4.2.10 on 2024-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("username", models.CharField(max_length=24, unique=True)),
                (
                    "phone",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("is_verified", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_banned", models.BooleanField(default=False)),
                ("is_warned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("votes", models.IntegerField(default=0, null=True)),
                (
                    "display_name",
                    models.CharField(default=None, max_length=32, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="media/user/trollface.png",
                        null=True,
                        upload_to="media/user/",
                    ),
                ),
                ("telegram", models.URLField(blank=True, default=None, null=True)),
                ("instagram", models.URLField(blank=True, default=None, null=True)),
                ("facebook", models.URLField(blank=True, default=None, null=True)),
                ("twitter", models.URLField(blank=True, default=None, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["username"], name="users_user_usernam_65d164_idx"
                    )
                ],
            },
        ),
    ]
