# Generated by Django 4.2.10 on 2024-04-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
