# Generated by Django 4.2.10 on 2024-04-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notifications',
        ),
    ]
