# Generated by Django 4.2.10 on 2024-05-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_code_created_at_alter_code_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Account registration"),
                    ("restore", "Password restoration"),
                    ("change", "Phone number change"),
                ],
                default="register",
                max_length=8,
                null=True,
            ),
        ),
    ]
