# Generated by Django 4.2.10 on 2024-04-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default.png', null=True, upload_to='media/user/'),
        ),
    ]
