# Generated by Django 4.2.10 on 2024-05-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_code_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="code",
            name="type",
            field=models.CharField(
                choices=[
                    ("register", "Account registration"),
                    ("change", "Phone number change"),
                    ("reset", "Password reset"),
                ],
                default="register",
                max_length=8,
                null=True,
            ),
        ),
    ]
