# Generated by Django 4.2.10 on 2024-05-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_code_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="facebook",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="twitter",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
