# Generated by Django 4.2.10 on 2024-04-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=32, null=True)),
                ('post_title', models.CharField(default=None, max_length=200, null=True)),
                ('community_name', models.CharField(default=None, max_length=32, null=True)),
                ('community_link', models.CharField(default=None, max_length=32, null=True)),
                ('parent', models.IntegerField(default=0, null=True)),
                ('parent_user', models.IntegerField(default=0, null=True)),
                ('parent_username', models.TextField(default=None, max_length=32, null=True)),
                ('body', models.TextField(default=None, max_length=10000, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('downvotes', models.IntegerField(default=0, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('ratio', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownvoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UpvoteComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
            ],
        ),
    ]
