# Generated by Django 4.2.10 on 2024-03-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0011_post_posts_post_user_id_1547df_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=32, null=True)),
                ('community', models.CharField(default='cars', max_length=32, null=True)),
                ('parent', models.IntegerField(default=0, null=True)),
                ('body', models.TextField(max_length=2048, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('downvotes', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='comments_co_user_id_063857_idx'), models.Index(fields=['post'], name='comments_co_post_id_380fdd_idx'), models.Index(fields=['created_at'], name='comments_co_created_5f6a12_idx')],
            },
        ),
    ]
