# Generated by Django 4.2.10 on 2024-03-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_upvotes_914b30_idx',
        ),
        migrations.AlterField(
            model_name='comment',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['votes'], name='comments_co_votes_79efdf_idx'),
        ),
    ]
