# Generated by Django 4.2.10 on 2024-03-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_remove_post_posts_post_user_id_91a3ab_idx_and_more'),
        ('comments', '0002_remove_comment_comments_co_upvotes_914b30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
