# Generated by Django 4.2.10 on 2024-03-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
        ('comments', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='community_link',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, related_name='comment_community_link', to='communities.community', to_field='link'),
        ),
        migrations.AddField(
            model_name='comment',
            name='community_name',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, related_name='comment_community_name', to='communities.community', to_field='name'),
        ),
    ]
