# Generated by Django 4.2.10 on 2024-03-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_alter_post_community_link_alter_post_community_name_and_more'),
        ('communities', '0006_community_owner_username_alter_community_avatar_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0004_comment_community_link_comment_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='community',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='community_link',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='community_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent_username',
            field=models.TextField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post_title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
