# Generated by Django 4.2.10 on 2024-04-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_user_id_063857_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comments_co_post_id_380fdd_idx',
        ),
    ]
