# Generated by Django 4.2.10 on 2024-04-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_comment_ratio_upvotecomment_downvotecomment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['ratio'], name='comments_co_ratio_c1d389_idx'),
        ),
    ]
