# Generated by Django 4.2.10 on 2024-02-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.IntegerField(default=0, null=True)),
                ('posts', models.IntegerField(default=0, null=True)),
                ('comments', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
