# Generated by Django 4.2.10 on 2024-04-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(default=None, max_length=32, null=True)),
                ('name', models.CharField(default=None, max_length=32, null=True, unique=True)),
                ('link', models.CharField(default=None, max_length=32, null=True, unique=True)),
                ('description', models.TextField(default=None, max_length=1000, null=True)),
                ('members', models.IntegerField(default=0, null=True)),
                ('posts', models.IntegerField(default=0, null=True)),
                ('comments', models.IntegerField(default=0, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('downvotes', models.IntegerField(default=0, null=True)),
                ('rules', models.TextField(default=None, max_length=5000, null=True)),
                ('avatar', models.ImageField(default='community/default.png', null=True, upload_to='community/')),
                ('banner', models.ImageField(default='community/default.png', null=True, upload_to='community/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='communities.community')),
            ],
        ),
    ]
