# Generated by Django 4.2.10 on 2024-04-17 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercommunity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='usercommunity',
            unique_together={('user', 'community')},
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_3031a9_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['link'], name='communities_link_5f53cc_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['created_at'], name='communities_created_4d42e1_idx'),
        ),
    ]
