# Generated by Django 4.2.10 on 2024-03-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_remove_community_comments_remove_community_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bio',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='downvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='owner',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='rules',
            field=models.TextField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='upvotes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=1024, null=True),
        ),
    ]
