# Generated by Django 4.2.10 on 2024-03-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_community_bio_community_downvotes_community_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='profile_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
