# Generated by Django 4.2.10 on 2024-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_community_profile_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='community',
            name='profile_url',
        ),
        migrations.RemoveField(
            model_name='community',
            name='title',
        ),
        migrations.AddField(
            model_name='community',
            name='avatar_url',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='banner_url',
            field=models.CharField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='link',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(default=None, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='rules',
            field=models.TextField(default=None, max_length=5000, null=True),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_3031a9_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['link'], name='communities_link_5f53cc_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['created_at'], name='communities_created_4d42e1_idx'),
        ),
    ]
