# Generated by Django 4.2.10 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='owner_username',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='avatar_url',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='banner_url',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
    ]
