# Generated by Django 4.2.10 on 2024-03-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_community_owner_username_alter_community_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='comments',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='posts',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
