# Generated by Django 4.2.10 on 2024-04-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownvotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=32, null=True)),
                ('user_avatar', models.CharField(default=None, max_length=1000, null=True)),
                ('community_name', models.CharField(default=None, max_length=32, null=True)),
                ('community_link', models.CharField(default=None, max_length=32, null=True)),
                ('community_avatar', models.CharField(default=None, max_length=1000, null=True)),
                ('title', models.CharField(default=None, max_length=200, null=True)),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], default='text', max_length=5, null=True)),
                ('body', models.TextField(default=None, max_length=10000, null=True)),
                ('image', models.ImageField(default='post/gordon.png', null=True, upload_to='post/')),
                ('link', models.URLField(default='', max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visits', models.IntegerField(default=0, null=True)),
                ('upvotes', models.IntegerField(default=0, null=True)),
                ('downvotes', models.IntegerField(default=0, null=True)),
                ('comments', models.IntegerField(default=0, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('ratio', models.FloatField(default=1.0, null=True)),
                ('score', models.FloatField(default=1.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UpvotePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
