# Generated by Django 4.2.10 on 2024-05-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_edited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="post",
            name="deleted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 28, 7, 27, 45, 554091, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 28, 7, 28, 4, 173677, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
