# Generated by Django 4.2.10 on 2024-05-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_updated_at_post_deleted_post_deleted_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
