# Generated by Django 4.2.10 on 2024-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_community_avatar_remove_post_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
    ]
