# Generated by Django 4.2.10 on 2024-05-28 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_alter_post_deleted_at_alter_post_edited_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="deleted_at",
        ),
    ]
