# Generated by Django 4.2.10 on 2024-02-22 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_remove_community_comments_remove_community_posts_and_more'),
        ('posts', '0005_post_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default='cars', null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community', to_field='name'),
        ),
    ]
