# Generated by Django 4.2.10 on 2024-03-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_comments_co_upvotes_914b30_idx_and_more'),
        ('posts', '0013_remove_post_posts_post_user_id_91a3ab_idx_and_more'),
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
        ('users', '0005_user_users_user_usernam_65d164_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_comments',
            field=models.ManyToManyField(related_name='downvoted_by', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='downvoted_posts',
            field=models.ManyToManyField(related_name='downvoted_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_warned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_communities',
            field=models.ManyToManyField(related_name='joined_by', to='communities.community'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_comments',
            field=models.ManyToManyField(related_name='saved_by', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(related_name='saved_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_comments',
            field=models.ManyToManyField(related_name='upvoted_by', to='comments.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_posts',
            field=models.ManyToManyField(related_name='upvoted_by', to='posts.post'),
        ),
        migrations.AddField(
            model_name='user',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
