# Generated by Django 4.2.10 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_likes_user_downvoted_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
    ]
