# Generated by Django 4.2.10 on 2024-04-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_communities',
            new_name='joined',
        ),
    ]
