# Generated by Django 4.2.10 on 2024-04-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_joined_communities_user_joined'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_url',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='downvoted_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='downvoted_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='saved_posts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='upvoted_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default=models.CharField(max_length=32, unique=True), max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(default=None, max_length=10000, null=True),
        ),
    ]
