# Generated by Django 4.2.10 on 2024-04-17 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='community_avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user_avatar',
        ),
    ]
