# Generated by Django 4.2.10 on 2024-03-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='admin', max_length=32, null=True),
        ),
    ]
