# Generated by Django 4.2.10 on 2024-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_posts_post_communi_92b6cb_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='posts_post_user_id_1547df_idx'),
        ),
    ]
