# Generated by Django 4.2.10 on 2024-03-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_posts_post_user_id_1547df_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_user_id_1547df_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user_id'], name='posts_post_user_id_91a3ab_idx'),
        ),
    ]
