# Generated by Django 4.2.10 on 2024-03-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
        ('posts', '0012_remove_post_posts_post_user_id_1547df_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_user_id_91a3ab_idx',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='comments',
            new_name='visits',
        ),
        migrations.AddField(
            model_name='post',
            name='ratio',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.FloatField(default=1.0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='votes',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default='all', null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='posts_post_user_id_1547df_idx'),
        ),
    ]
