# Generated by Django 4.2.10 on 2024-03-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_remove_community_bio_remove_community_profile_url_and_more'),
        ('posts', '0013_remove_post_posts_post_user_id_91a3ab_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='community_link',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, related_name='community_link', to='communities.community', to_field='link'),
        ),
        migrations.AddField(
            model_name='post',
            name='community_name',
            field=models.ForeignKey(default='all', on_delete=django.db.models.deletion.CASCADE, related_name='community_name', to='communities.community', to_field='name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='communities.community'),
        ),
        migrations.AlterField(
            model_name='post',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
