# Generated by Django 4.2.10 on 2024-03-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_community_link_post_community_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community_link',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='community_name',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
