# Generated by Django 4.2.10 on 2024-04-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
