# Generated by Django 4.2.10 on 2024-04-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_remove_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('link', 'Link')], default='text', max_length=5, null=True),
        ),
    ]
