# Generated by Django 4.2.10 on 2024-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.URLField(default='', max_length=10000, null=True),
        ),
    ]
