# Generated by Django 4.2.10 on 2024-04-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_upvotepost_savepost_downvotepost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvotepost',
            unique_together=set(),
        ),
    ]
