# Generated by Django 4.2.10 on 2024-04-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_downvotepost_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_communi_92b6cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_user_id_1547df_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['score'], name='posts_post_score_18d625_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['votes'], name='posts_post_votes_89c987_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['ratio'], name='posts_post_ratio_90e43f_idx'),
        ),
    ]
