# Generated by Django 4.2.10 on 2024-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_post_posts_post_communi_92b6cb_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downvoted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='saved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='upvoted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
