# Generated by Django 4.2.10 on 2024-04-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_post_downvoted_post_hidden_post_saved_post_upvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downvoted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='post',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvoted',
        ),
    ]
