# Generated by Django 4.2.10 on 2024-05-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_alter_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="comment",
            name="deleted",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="edited_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
