# Generated by Django 4.2.10 on 2024-05-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_remove_comment_updated_at_comment_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="body_text",
            field=models.TextField(default=None, max_length=10000, null=True),
        ),
    ]
