# Generated by Django 4.2.10 on 2024-02-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='community',
            name='posts',
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
