# Generated by Django 4.2.10 on 2024-04-18 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply', 'Reply'), ('other', 'Other')], default='other', max_length=13, null=True)),
                ('parent_post', models.IntegerField(default=None, null=True)),
                ('parent_comment', models.IntegerField(default=None, null=True)),
                ('user', models.IntegerField(default=None, null=True)),
                ('community', models.CharField(default=None, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comment')),
                ('parent_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
