# Generated by Django 4.2.10 on 2024-04-28 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="parent_user",
            new_name="receiver",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="sender",
        ),
    ]
