# Generated by Django 4.2.10 on 2024-04-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='community',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
